apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: catalogue
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  # these labels are replicaset labels
  labels:
    project: roboshop
    tier: backend
    component: catalogue
spec:
  replicas: 1
  selector:
    # using these labels replica set selects the pod
    matchLabels:
      project: roboshop
      tier: backend
      component: catalogue
  # This is pod definition, pod is subset of replicaset
  template:
    metadata:
      labels:
        project: roboshop
        tier: backend
        component: catalogue
    spec:
      containers:
      - name: catalogue
        image: dockerlearn255/catalogue:1.0.0
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
             memory: "128Mi"
             cpu: "100m"
        readinessProbe:
          # httpGet:
          #   path: /health
          #   port: 8080
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5 # how many seconds to wait before starting the probe
          failureThreshold: 2  # how many times to retry before considering the container unhealthy
          periodSeconds: 10  # how many seconds to wait before next probe
        livenessProbe:
          httpGet:  
            path: /health
            port: 8080
          failureThreshold: 2
          periodSeconds: 10  
        envFrom:
        - configMapRef:
            name: catalogue

---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: catalogue
spec:
  selector:
    # labels are used as selectors
    project: roboshop
    tier: backend
    component: catalogue  
  ports:
  - protocol: TCP
    port: 8080 # service port
    targetPort: 8080 # container port

